server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      #在此配置要绑定的rabbitmq的服务信息
      binders:
        #表示定义的名称，用于binding整合
        defaultRabbit:
          #消息组件类型
          type: rabbit
          #设置rabbitmq的相关环境配置
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      #服务的整合处理
      bindings:
        #这个名字是一个通道的名称
        input:
          #表示要使用的Exchange名称定义
          destination: studyExchange
          #设置消息类型，本次为json，文本则设置“text/plain”
          content-type: application/json
          #设置要绑定的消息服务的具体设置
          binder: defaultRabbit
          group: A
eureka:
  client:
    #表示是否将自己注册进Eureka，默认为true
    register-with-eureka: true
    #表示是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合Ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka,,http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: stream-consumer8802
    prefer-ip-address: true
    #设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 2
    #如果现在超过了5秒的间隔（默认是90秒）
    lease-expiration-duration-in-seconds: 5
